### PR TITLE
Improve graph of Model page/view

### LINKED ISSUE #61: The model graph does not have axis labels
From https://bl.ocks.org/d3noob/23e42c8f67210ac6c678db2cd07a747e

```
    // text label for the x axis
    svg.append("text")
      .attr("transform",
            "translate(" + (width/2) + " ," +
                           (height + margin.top + 20) + ")")
      .style("text-anchor", "middle")
      .text("Date");

    // text label for the y axis
    svg.append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", 0 - margin.left)
      .attr("x",0 - (height / 2))
      .attr("dy", "1em")
      .style("text-anchor", "middle")
      .text("Value");
```

### PR DESCRIPTION
**Pull request by Bachibouzouk**
- Make the graph reactive
- Add labels for the axis

Fix #61

### CODE REVIEW

**Comment by Matoo125** [comment]
hmm, there is this big X over the graph, and code for axis annotation doesn't seem to be working. Also resizing when changing screen size is not working without refresh (that is ok, but according to code it's intended to work).

**Comment by Bachibouzouk** [comment]
> hmm, there is this big X over the graph, and code for axis annotation doesn't seem to be working. Also resizing when changing screen size is not working without refresh (that is ok, but according to code it's intended to work).

@Matoo125 - That was the code I pushed before you merged, I had to solve conflicts before pushing again, the x was just there to prove that the window would rescale

**Comment by Matoo125** [comment]
I still don't see the axis annotations and live rescaling is not working for me (it does after refresh)

covid

**Comment by Bachibouzouk** [comment]
> I still don't see the axis annotations and live rescaling is not working for me (it does after refresh)

It was working with fondation :'(. I give up on that one I think plotly.js does a good job wrapping functionalities of d3.js and allow intuitive setting of basic components of a graph (I think one should not have to fight to set labels on a graph)

**Comment by hnykda** [comment]
Yeah, I can see the value of plotly abstraction after seeing how low level d3.js is :grimacing: .

**Comment by Matoo125** [comment]
Ok, Iet me look at it

**Comment by Matoo125** [comment]
should be good @hnykda  can you review?

**Pull request merged**
