### PR TITLE
Rework model UI

### PR DESCRIPTION
**Pull request by Discordius**
I've been working with Jacob on this over the weekend. This updates the frontpage UI to be much more functional on mobile, and more broadly prioritize information better. There are still a lot of improvements to be made, but I think it's a significant overall improvement in terms of UI. Here is a screenshot: 

Screen Shot 2020-03-29 at 9 19 59 PM

And here is a screenshot for mobile: 

Screen Shot 2020-03-29 at 9 02 23 PM

The biggest code-quality problem with this PR is how I managed all the CSS styling. Most of the previous styling was done in a column layout, combined with a lot of attribute-style classes (i.e. "left-align" as a class). I sadly don't have a lot of experience in that CSS style, and after an hour I gave up on trying to stick with the existing CSS style and moved towards a more classical "just have about one class per element" style. Since we don't have SCSS processing set up, this created some duplications of CSS, since I couldn't use any mixins. I also just added all of my CSS in one big block in `main.css` which makes that file overall harder to navigate, though it seemed overall to already not have super much structure.

Overall, if this were a project with a longer lifespan, I would probably spend significant additional time cleaning up the CSS, but I am sadly running out of time and it seems important to ship this sooner rather than later. 

I also made a lot of UI prioritization decisions that I discussed with Jacob. Happy to give more context on any of these. The biggest ones that I can think of are: 

* Instead of having the "None", "Weak", etc. mitigation strengths, I now put things in percentages, since I think tons of people were confused what those different levels mean.
* Our estimate of the number of active infections at the current date is now in a bright color, making it a much more salient feature of the site.
* I generally brightened up the colors a bit and switched out the orange for a more vivid orange
* I got rid of all the expandable sections and just added the content of the expandable sections to the bottom, with small help icons that link to those sections at the top.

### CODE REVIEW

**Comment by hnykda** [comment]
I really like it and wants to merge this (if @lagerros has already approved). There are unfortunately some conflicts now. Would you be able to rebase it so we can merge?

**Comment by Discordius** [comment]
Seems good, will resolve he conflicts in an hour or so.

**Comment by hnykda** [comment]
Is this basically blocked by #301?

**Comment by Discordius** [comment]
Yep, blocked by that

**Comment by Discordius** [comment]
Closed in favor of #315

**Pull request closed without merging**
