### PR TITLE
Fix contact form styling

### PR DESCRIPTION
**Pull request by jeromezng**
## Overview
This pull request fixes the styling for the contact form on the /contact page

### Desktop Comparison
Before:
desktop-before
After:
desktop-after

### Mobile Comparison
Before:
mobile-before

After:
mobile-after

### CODE REVIEW

**Comment by hnykda** [comment]
Looks great!

**Comment by Mati-Roy** [comment]
> When clicking “Contact”, the hover at the top is still over “Model”

was this fixed?

**Comment by Matoo125** [comment]
I don't think so

**Comment by Mati-Roy** [comment]
ok, I'll add it to another PR with miscellaneous UI fixes

**Pull request merged**
