### PR TITLE
Small UI/UX tweaks for Model and About pages

### PR DESCRIPTION
**Pull request by rakyi**
Best checked by running my branch locally.

### CODE REVIEW

**Comment by hnykda** [comment]
Thank you so much, díky moc!

**Comment by hnykda** [comment]
@jeromezng could you please check it out and merge if all good? @rakyi is part of our CZ EA chapter, have good experience.

**Comment by hnykda** [comment]
@rakyi would you mind rebasing to master please? Then I would merge it.

**Comment by rakyi** [comment]
Rebased.

**Pull request merged**
