### PR TITLE
Model visualisation's legend's colors

### PR DESCRIPTION
**Pull request by Mati-Roy**
part of https://github.com/epidemics/covid/issues/126

### CODE REVIEW

**Comment by Mati-Roy** [comment]
issues: https://github.com/epidemics/covid/issues/126 , https://github.com/epidemics/covid/issues/151

**Comment by lagerros** [comment]
@wolverdude this is a high priority PR and it also involves some d3, so maybe you could have a look? (You're assigned as a reviewer anyway)

**Comment by wolverdude** [comment]
@lagerros: The error is because this code is still using an outdated data set.

Unfortunately, I can't fix this easily because there are a ton of merge conflicts between this and #159. If it's critical to have this merged before either @hnykda or @Mati-Roy are back online, I can do it, but it's gonna take me a lot longer than it would either of them.

**Comment by Matoo125** [comment]
This will probably create quite a lot of conflict with https://github.com/epidemics/covid/pull/161 .. I'd rather merge first and just bring the relevant code to the new version. Legend will need to come from data, won't be hard-written.
 It should work like this https://github.com/epidemics/covid/pull/161/files#diff-58cc30c2dfe9e8a85641965af7c25cfdR268

**Comment by wolverdude** [comment]
@Matoo125, Is this a request that I move forward with the merge immediately? A quick way to do it would be to clobber all of @hnykda's changes in `result-event-evaluation.html` and then let him solve the issues when he gets back online.

**Comment by Matoo125** [comment]
No I don't want to merge this, it's not compatible with https://github.com/epidemics/covid/pull/161 ... I think we should either ignore this PR and do the changes from 161 or try to merge them

**Comment by Matoo125** [comment]
The only relevant code is this and bit of css

```
var svg = d3
  .select("#my_dataviz")
  .attr("class", "row")
  .style("width", "100%")
  .append("div")
  .attr("class", "col-md-9 col-sm-12")
  .append("svg")
  .attr("preserveAspectRatio", "xMinYMin meet")
  .attr("viewBox", "0 0 750 750")
  .classed("svg-content", true)
  .append("g")
  .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

// Legend
d3.select("#my_dataviz")
  .append("div")
  .attr("class", "col-md-3 col-sm-12")
  .style("padding", "0px")
  .append("div")
  .attr("class", "legend")
  .append("div")
  .html(
    `<span class="color1">
      Weak seasonality
      <br/>
      Weak reduction in air travel
    </span>
    <br>
    <br>
    <span class="color2">
      Medium seasonality
      <br/>
      Weak reduction in air travel
    </span>
    <br>
    <br>
    <span class="color3">
      Strong seasonality
      <br/>
      Weak reduction in air travel
    </span>
    <br>
    <br>
    <span class="color41">
      Weak seasonality
      <br/>
      Strong reduction in air travel
    </span>
    <br>
    <br>
    <span class="color5">
      Medium seasonality
      <br/>
      Strong reduction in air travel
    </span>
    <br>
    <br>
    <span class="color6">
      Strong seasonality
      <br/>
      Strong reduction in air travel
    </span>`
  );
```

**Comment by wolverdude** [comment]
Okay. That essentially means this PR is dead. I'll leave it open for now, but @Mati-Roy will basically have to reimplement everything.

I'm wondering if there are better ways to divide the work. We've got several people working on the different features in the same files simultaneously, and I'm guessing this isn't the first time that a PR became unmergeable almost immediately. Currently, it doesn't seem safe to leave your PR open overnight.

@hnykda @jeromezng, do you have any thoughts on how we could avoid this wasted effort? Maybe we could group similar issues and ensure that only one PR is open for any given issue group?

**Comment by jeromezng** [comment]
> @hnykda @jeromezng, do you have any thoughts on how we could avoid this wasted effort? Maybe we could group similar issues and ensure that only one PR is open for any given issue group?

We already have work grouped using labels: 
- Frontend
- D3
- Data
- DevOps

In this case it looks like Data changed what's consumed by Frontend and D3. Since we have an async working style that's quite decentralized w/ volunteers, I think the best way to avoid this is 
over-communicating in slack what you're working on especially if it affects another group.

**Pull request merged**
