### PR TITLE
Load the data from the notion database

### LINKED ISSUE #78: For each country-specific view (view 1), display text of containment measures from containment measures database
The measures for each location can be found in this database: https://www.notion.so/977d5e5be0434bf996704ec361ad621d?v=aa8e0c75520a479ea48f56cb4c289b7e

Not yet implemented: parser from notion to pandas or csv

```
import os
import keyring


from notion.client import NotionClient

# Obtain the `token_v2` value by inspecting your browser cookies on a logged-in session on Notion.so
# I used keyring to save the token locally
token_v2 = keyring.get_password("notion", "token")
client = NotionClient(token_v2=token_v2)

cv = client.get_collection_view(
    "https://www.notion.so/977d5e5be0434bf996704ec361ad621d?v"
    "=aa8e0c75520a479ea48f56cb4c289b7e"
)
# here are the fields which interest us
# Country
# Description of measure implemented
# Keywords
# Source


# Run a filtered/sorted query using a view's default parameters
result = cv.default_query().execute()
for row in result:
    print(row.description_of_measure_implemented)
```

The containment measures could be in the sidebar with similar design as the previous one (one entry for each date, descending)

### PR DESCRIPTION
**Pull request by Bachibouzouk**
Fix #78 

Note: there is a way to communicate directly with the database
to get the data, described on the Issue

The d3 hack to update the select seem to allow the options to be loaded only once via normal template at initialisation. The data are not empty, however and direct url query works, i.e. `http://127.0.0.1:8000/model?country=France`

### CODE REVIEW

**Comment by Bachibouzouk** [comment]
@Matoo125, @OAGr could you fix the d3 hack so that the state is reflected in the url query string?

**Comment by Matoo125** [comment]
url fixed

**Comment by Matoo125** [comment]
IDN, guess we can just change the url.... I'd just merge if python code is good.

**Comment by Matoo125** [comment]
sorry, I didn't realize it was added in this PR, seems totally useless, removed

**Comment by Matoo125** [comment]
If I understand the task, it should show only measures for a selected country, but we still have list of cities instead, so I think it's good for now

**Comment by Matoo125** [comment]
hmm, it seems there is a bit of code that isn't working, such as getting the country capital, but I'd prefer to merge it so we are not creating distance from master, and fix it later

**Comment by Bachibouzouk** [comment]
> Sorry, why do we have jquery in statics? (given that we are serving them via fastapi server, it's super slow, so this is going to slow things even more)
> 
> Otherwise looks good

I thought static files were faster, I don't have much experience with speed of serving code

**Comment by Bachibouzouk** [comment]
> If I understand the task, it should show only measures for a selected country, but we still have list of cities instead, so I think it's good for now

I didn't know how to change the input of the selectButton (I think those were dummy data at the time anyway), @lagerros told me to just match the capital with the country

**Comment by hnykda** [comment]
Serving static files via our server is definitely slower than using some CDN.

**Comment by Bachibouzouk** [comment]
> hmm, it seems there is a bit of code that isn't working, such as getting the country capital, but I'd prefer to merge it so we are not creating distance from master, and fix it later

I tested the code in a jupyter notebook and it worked, some capital correspond to some country which don't have any measures yet though (that's why I printed the args, to see if the data was supposed to be empty before it is sent to the template)


> Serving static files via our server is definitely slower than using some CDN.

Do you know a good reference where I could learn what is slow and what is fast? As my background is physics, I lack knowledge in these serving standards!

**Comment by Matoo125** [comment]
we already have different data, so it doesn't matter.

**Pull request merged**
