### PR TITLE
Data v4

### PR DESCRIPTION
**Pull request by mathijshenquet**
I built on #365, I hid the `/measures` page for now.

I used this branch to generate the data: https://github.com/epidemics/epimodel/pull/29

Some temporary hacks I had to do:
1. Population was not included in the gleamviz dataset so I'm using the UN Age dist data to compute the population.
2. Gleamviz trace data was was a factor of 1000 to low this time. Previously it was infected per 1000 and now it is infected per 0.001.

### CODE REVIEW

**Comment by wolverdude** [comment]
So I'm gathering this is not just a simple update to v4, but it also includes some larger changes and refactors from your containment measures branch? It'll take a little more time/focus to review, but I'll take a look.

Broader point here: With the addition of `region-dropdown.ts`, I think we're finally getting to the point of complexity where a framework would pay off, and in fact it looks like that file is starting to verge on building its own framework. There's a fairly narrow window here before we will regret not adopting a well-established framework now, so I suggest we open up the discussion in Slack.

**Comment by mathijshenquet** [comment]
Fixes #336

**Comment by mathijshenquet** [comment]
I know its a bit suboptimal that this is going together with #365. But there was some much needed refactoring in that branch that I did not want to merge that in later. The front facing changes are all hidden away behind the `/measures` route so we can discuss the page itself later.

**Comment by mathijshenquet** [comment]
In this PR I also decouple the wire data format from the internal data format in this folder: https://github.com/epidemics/covid/tree/data-v4/frontend/models

In there there is also:
https://github.com/epidemics/covid/tree/data-v4/frontend/models/v4

we could extend this/place this somewhere else to be the 'format' data-v4 spec. It currently just contains the gleamviz model traces stuff from `dataext-*.json`.

**Pull request merged**
