### PR TITLE
Go over setup instructions (using conda).

### PR DESCRIPTION
**Pull request by mkcor**
Dear developers,

Thank you for the awesome work!

I just got set up with the project using conda. I'm therefore suggesting these changes to the README based on my experience of right now.

Some details:

* leaving http://localhost:8000 (without back ticks) renders the hyperlink;
* code blocks may be either [fenced or non-fenced](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks); I introduced some inconsistency in the file by using non-fenced (indented) code blocks; I prefer them because they imply typing fewer characters;
* "using conda" is an alternative to "using docker" so I think it should be at the same level (level-2 title, in this case);
* installing Poetry with pip is [not recommended](https://python-poetry.org/docs/#alternative-installation-methods-not-recommended).

Best,
Marianne

### CODE REVIEW

**Comment by mkcor** [comment]
PS: I added 2aba3ea because a README with a screenshot a lot more enticing!

**Comment by mkcor** [comment]
PPS: I had to run `python -m pip install -U h11` to go through `poetry install` successfully (I ran into ERROR: Could not find a version that satisfies the requirement h11==0.9.0).

**Comment by hnykda** [comment]
:heart: 

Do you expect more to come? :grin: Should I add you to the collaborators?

**Comment by mkcor** [comment]
@hnykda Ok! :wink:

**Comment by Bachibouzouk** [comment]
Hello @mkcor :)

**Pull request merged**
