### PR TITLE
Presentation of results

### PR DESCRIPTION
**Pull request by hrosspet**

### CODE REVIEW

**Comment by hnykda** [comment]
Related #8

**Comment by hnykda** [comment]
Will you be able to incorporate it into the current bokeh serving mechanism e.g. instead of `app1` as I mentioned in #13 ?

**Comment by hrosspet** [comment]
Yes, I have it working. Will clean up the code tomorrow & push.

**Comment by hnykda** [comment]
@hrosspet I did a massive amount of changes and to make it easier for you, I rebased this branch to the current master and it's here: https://github.com/epidemics/covid/pull/23. I propose to close this one and you continue there.

**Pull request closed without merging**
